services:
  zonnebrand:
    build: .
    container_name: zonnebrand
    restart: unless-stopped

    env_file:
      - .secrets/keys

    volumes:
      - ./dashboard:/app/dashboard

    command: python zonnebrand/zonnebrand.py --provider zonneplan